### ISSUE TITLE
High spike in Gas consumption

### ISSUE THREAD

**Issue by WayeeWang** [DCSBL/ha-homewizard-energy#27]
![Screenshot_20210428_103751](https://user-images.githubusercontent.com/42268804/116375832-f139b980-a80f-11eb-8589-cc8e91d97507.jpg)
**Describe the bug**
I have a P1 connected to the digital meter, and this integration installed for Home Assistant.

A few days ago I observed a huge spike (a sudden ±1800 m^3 consumption) in the gas consumption collected by P1, both seen in Home Assistant, and the HomeWizard companion app on the smart phone.

This spike totally ruined the historical data (using utility component) of the consumptions and calculated costs, as expected. However, in HomeWizard app, the daily consumption and its cost look normal (i.e. that spike was not taken into account).

Do you know why that spike was present? And since the historical data in HA is now corrupted due to the wrong data, is there a way to correct/reset them?

**Comment by DCSBL** [comment]
Thank you for this bug report :+1:

This is a issue that lays in the wireless communication between the gas meter and the energy meter. In very rare cases the gas meter sends corrupted data to the engermeter. The energy meter sees this as 'correct' and sends it as-is to the P1 meter with valid checksum, so the P1 meter can't detect that there is some invalid data present. 

I think that because the utility meter calculates the difference between 2 values, the result will be `<current_real_value> - 0 = <the spike you see>`.

**How you can fix this**
You have to dive into your database and fix it manually. Then, In the mean time, please set your poll-interval to something like 30 seconds (this issue only happens when above situations occurs and HA reads the API at exactly that moment. Increasing the poll interval will will reduce the change this can happen. 

_Go to Configuration > Integrations > <your P1 meter> > Options > set `Override default poll interval` and the value._

**Permanent fix**
HomeWizard will roll out a new firmware version very soon, it adds extra checks to see if the gas meter sends valid data. I will let you know when this is pushed out.

**Comment by WayeeWang** [comment]
Thank you very much for the swift and clear explanation.

Once the new firmware is rolled out, will P1 update by itself. I don't seem to find the update option in the app.

BTW, great work from you (and maybe also your colleagues), of making this excellent small device and the HA component. I use it to automate our electric heater and AC when there is excess energy. Working like a charm! Much appreciated.

**Comment by DCSBL** [comment]
Thank you for your compliments, I will pass it on!

When HomeWizard starts with the rollout, the update will install automatically.

**Comment by WayeeWang** [comment]
Great, looking forward to it!

In the meantime, I think I've just found a workaround to solve this temporarily.

Utility Meter component has a variable "net_consumption" which is "false" by default.

By setting it to "true", it will allow the values to be both negative and positive, according to the documentation. 

So if I'm not mistaken, this spike would be removed by first having a big negative diff, and then a big positive diff.

**Comment by DCSBL** [comment]
HomeWizard have started to roll-out firmware `2.13`. It will be installed automatically within a few days when your device is connected to the internet, you can find the version in your HomeWizard Energy app. This firmware should solve the problem you have described. 

Please feel free to reopen this issue or contact HomeWizard directly when it happens again, or open a new issue when you have any other problem or idea with the integration.
