### ISSUE TITLE
Add cost information

### ISSUE THREAD

**Issue by Techwolf12** [DCSBL/ha-homewizard-energy#29]
**Is your feature request related to a problem? Please describe.**
It would be a nice to have information on how much electricity and gas costs you.

**Describe the solution you'd like**
A input of T1, T2 & gas costs for both import and export, and having some default costs added as sensors, like "Costs today" or "Costs this month"

**Describe alternatives you've considered**
Adding this sensor myself based on the data here in HomeAssistant (could do that too, but was wondering if it would be on the roadmap for here)

**Comment by DCSBL** [comment]
Thank you for this idea. I think I won’t implement that here, because the only purpose of this integration is to expose HomeWizard Energy to Home Assistant. 

Please take a look at the [HA thread](https://community.home-assistant.io/t/custom-component-homewizard-energy-wifi-p1-meter/227441/230), there are a lot of examples how to integrate costs within Home Assistant

**Comment by Techwolf12** [comment]
Understandable! Thanks for building this!
